version: '3'
services:
    php-apache:
        image: mitlabs/apache-php7.3
        ports:
            - 8080:80
        volumes:
            - ./unionatlantica:/var/www/html
        links:
            - 'mariadb'
    mariadb:
        image: mariadb:10.3
        volumes:
            - ./db:/var/lib/mysql
        environment:
            TZ: 'America/Argentina/Buenos_Aires'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
            MYSQL_ROOT_PASSWORD: 'rootpassword'
            MYSQL_USER: 'muser'
            MYSQL_PASSWORD: 'bpassword'
            MYSQL_DATABASE: 'lampdb'
        ports:
            - 3336:3306
