alias t='tree -L 1 --gitignore -a'
alias tt='tree -L 2 --gitignore -a'
alias c='nvim $HOME/.config/nvim/init.lua'
alias u='updatedb -l 0 -e $PWD/node_modules -U . -o plocate.bd'
alias f='locate -d plocate.db'
alias v='nvim'
